# PostGRES
development:
  adapter: postgresql
  database: csv_importer_dev
  username: postgres
  password: password
  pool: 5
  timeout: 5000

# MySQL
development_mysql:
  adapter: mysql2
  database: csv_importer_dev
  username: root
  password:
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: csv_importer_test
  username: root
  password:
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: csv_importer_prod
  username: root
  password:
  pool: 5
  timeout: 5000
